# ベースイメージとして Ruby 3.x を使用
FROM ruby:3.3.6

# Node.js と Yarn をインストール
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - \
  && apt-get update -qq \
  && apt-get install -y nodejs yarn

# 必要なライブラリをインストール
RUN apt-get install -y \
  libpq-dev \
  build-essential \
  libcurl4-openssl-dev \
  libssl-dev \
  libreadline-dev \
  zlib1g-dev \
  git

# 作業ディレクトリを設定
WORKDIR /app

# Gemfile と Gemfile.lock を先にコピーして bundle install を実行
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーションのソースコードをコンテナにコピー
COPY . .

# ポート3000を公開
EXPOSE 3000

# Railsアプリケーションを起動
CMD ["rails", "server", "-b", "0.0.0.0"]
